### ISSUE TITLE
希望增加功能：全屏模式隐藏

### ISSUE THREAD

**Issue by nsfoxer** [christorange/VerticalFox#13]
您的代码相当赞。之前使用tree tab，最大的问题是tree tab并不是浮动的，在扩展sidebar时会导致浏览器的页面width改变，从而使浏览器需要一直刷新页面布局，相当损耗资源。而您的这个布局完美解决了此问题。
  但我希望可能需要的额外几个功能：
  - 全屏模式下隐藏sidebar
  - sidebar右侧（或左侧）增加1px的阴影

第一个功能我找到相关解决方案：
```css
  #main-window[inFullscreen="true"] #sidebar-box,
#main-window[inFullscreen="true"] #sidebar-splitter {
  display: none !important;
  width: 0px !important;
}
 
#main-window[inFullscreen="true"] #appcontent {
margin-left: 0px;
}
```

第二个功能我并不清楚如何实现。=_=

我认为第一个功能是相当有用。希望可以补充。

另外，由于我使用Linux下的Gnome桌面环境，这里再分享一下我的`userChorme.css`
``` css
#main-window[inFullscreen="true"] #sidebar-box,
#main-window[inFullscreen="true"] #sidebar-splitter {
  display: none !important;
  width: 0px !important;
}
 
#main-window[inFullscreen="true"] #appcontent {
margin-left: 0px;
}
#titlebar {
  display: none;
}

#sidebar-header {
    display: none;
}
/* AUTO HIDE SIDE BAR */

#sidebar-box {
	--uc-sidebar-width: 44px; 
	--uc-sidebar-hover-width: 260px;
	--uc-autohide-sidebar-delay: 1ms; /* Waiting time before hiding sidebar */
	position: relative;
	min-width: var(--uc-sidebar-width) !important;
	width: var(--uc-sidebar-width) !important;
	max-width: var(--uc-sidebar-width) !important;
	z-index: 100;
}

#sidebar-box[positionend] {
	direction: rtl;
}
#sidebar-box[positionend] > * {
	direction: ltr;
}

#sidebar-box[positionend]:-moz-locale-dir(rtl) {
	direction: ltr;
}
#sidebar-box[positionend]:-moz-locale-dir(rtl) > * {
	direction: rtl;
}

/* HIDE SIDE BAR IN FULL SCREEN */
/* #main-window[sizemode="fullscreen"] #sidebar-box {
	--uc-sidebar-width: 0px;
} */

#sidebar-splitter {
	display: none;
}

#sidebar-header {
	overflow: hidden;
	color: var(--chrome-color, inherit) !important;
}

#sidebar {
	transition: min-width 115ms linear var(--uc-autohide-sidebar-delay) !important;
	min-width: var(--uc-sidebar-width) !important;
	will-change: min-width;
}

#sidebar-box:hover > #sidebar {
	min-width: var(--uc-sidebar-hover-width) !important;
	transition-delay: 0ms !important;
}

.sidebar-panel {
	background-color: transparent !important;
	color: var(--newtab-text-primary-color) !important;
}

.sidebar-panel #search-box {
	-moz-appearance: none !important;
	background-color: rgba(249, 249, 250, 0.1) !important;
	color: inherit !important;
}

/* Add sidebar divider and give it background */

#sidebar,
#sidebar-header {
	background-color: inherit !important;
/* 	border-inline: 1px solid rgb(80, 80, 80); */
	border-inline-width: 0px 1px;
}

#sidebar-box:not([positionend]) > :-moz-locale-dir(rtl),
#sidebar-box[positionend] > * {
	border-inline-width: 1px 0px;
}

/* Move statuspanel to the other side when sidebar is hovered so it doesn't get covered by sidebar */

#sidebar-box:not([positionend]):hover ~ #appcontent #statuspanel {
	inset-inline: auto 0px !important;
}
#sidebar-box:not([positionend]):hover ~ #appcontent #statuspanel-label {
	margin-inline: 0px !important;
	border-left-style: solid !important;
}

```

**Comment by christorange** [comment]
感谢你的建议与代码。
全屏模式隐藏有更简洁的代码实现：
```CSS
#main-window[inFullscreen="true"] #sidebar-box {
  --uc-sidebar-width: 0px;
}
```
其实就是注释 `/*HIDE SIDE BAR IN FULL SCREEN*/` 下的代码，因为我用错了选择器不生效所以先注释掉了，感谢你发现正确实现。

侧边栏阴影可以用 `drop-shadow` 实现：
```CSS
#sidebar-box{
  filter: drop-shadow(1px 0px 5px rgba(0, 0, 0, 1)) !important;
}
```
效果：
![image](https://github.com/christorange/VerticalFox/assets/85213835/ef65f5fd-baf0-47cf-b4d5-4ce36bf14259)

你可以调整参数来得到自己想要的样式。
