### ISSUE TITLE
URL previews missing

### ISSUE THREAD

**Issue by 5xyT3** [christorange/VerticalFox#32]
Normally when you hover the mouse over a link, its URL would appear in the bottom left hand corner of the window. Using this css removes this functionality. Can this be added back?

**Comment by alsa64** [comment]
Comment out line 48-51 in the chrome.css file, like this:
```css
 /* Suppress Link Destination Overlay */
 /* #statuspanel[type="overLink"] {
   display: none !important;
 } */
```
From a security perspective, hiding this is a no-go.
