### ISSUE TITLE
书签工具栏上多了一块空白

### ISSUE THREAD

**Issue by PumpkinJui** [christorange/VerticalFox#46]
![screenshot](https://github.com/christorange/VerticalFox/assets/76104432/11deef41-80cf-4966-94c8-5b56a01e2830)

如截图所示，在书签工具栏左侧有一块空白。鼠标位于其上时侧栏会自动展开，且无法点击书签工具栏。当且仅当设定为「只在新标签页显示」时会出现此问题。
使用 Firefox 125.0.3 和[这个主题](https://addons.mozilla.org/zh-CN/firefox/addon/dreamer-balanced/)。
（我知道 Sidebery 有书签的功能，但有点麻烦，我并不太想用。）

**Comment by Arthur-Huan** [comment]
If you move the sidebar to the right side, I found that removing `z-index: 100` under `#sidebar-box` seems to solve this.

If the sidebar is on the left, removing that will make the sidebar go under the webpage, and thus it won't work.

**Comment by triccsr** [comment]
I also have the same problem, and I am using default theme. 

The problem DOES NOT exist unless I paste sidebery_styles.css in this repo into sidebery's style editor, so the problem may be in sidebery_styles.css. But I know nothing about css and cannot find the bug.

A temporary solution from ChatGPT is replacing the 10 lines after `/*AUTO HIDE SIDE BAR*/` to:
```css
#sidebar-box {
  --uc-sidebar-width: 44px; 
  --uc-sidebar-hover-width: 260px;
  --uc-autohide-sidebar-delay: 1ms; /* Waiting time before hiding sidebar */
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index: 0;
  transition: z-index 0s linear 1ms; /* Ensure z-index changes with a delay */
}

#sidebar-box:hover {
  z-index: 100;
  transition-delay: 0s; /* Remove the delay when hovering */
}
```
It is OK when mouse is not hovering on sidebar.

**Comment by hartontw** [comment]
I've managed to get it working with:
```cs
#browser {
    z-index: 0 !important;
}

#sidebar-box {
	--uc-sidebar-width: 44px; 
	--uc-sidebar-hover-width: 450px;
	--uc-autohide-sidebar-delay: 1ms; /* Waiting time before hiding sidebar */
	position: relative;
	min-width: var(--uc-sidebar-width) !important;
	width: var(--uc-sidebar-width) !important;
	max-width: var(--uc-sidebar-width) !important;
	z-index: 1;
}
```

I'm not sure if this is going to trigger some undesired behaviour I'll report it if this happens.

自动翻译，抱歉：
我已设法使用此代码使其工作。
我不确定这是否会引发一些不良行为，如果发生这种情况，我会报告。

**Comment by digitalbarrito** [comment]
> I've managed to get it working with:
> 
> ```cs
> #browser {
>     z-index: 0 !important;
> }
> 
> #sidebar-box {
> 	--uc-sidebar-width: 44px; 
> 	--uc-sidebar-hover-width: 450px;
> 	--uc-autohide-sidebar-delay: 1ms; /* Waiting time before hiding sidebar */
> 	position: relative;
> 	min-width: var(--uc-sidebar-width) !important;
> 	width: var(--uc-sidebar-width) !important;
> 	max-width: var(--uc-sidebar-width) !important;
> 	z-index: 1;
> }
> ```
> 
> I'm not sure if this is going to trigger some undesired behaviour I'll report it if this happens.
> 
> 自动翻译，抱歉： 我已设法使用此代码使其工作。 我不确定这是否会引发一些不良行为，如果发生这种情况，我会报告。

This seems to have done the trick for me as well, not seeing any undesired behavior so far as well.

**Comment by stupienius** [comment]
This works on my windows11
```css
#navigator-toolbox {
   z-index:2 !important;
 }

#sidebar-box {
	--uc-sidebar-width: 44px; 
	--uc-sidebar-hover-width: 260px;
	--uc-autohide-sidebar-delay: 1ms; /* Waiting time before hiding sidebar */
	position: relative;
	min-width: var(--uc-sidebar-width) !important;
	width: var(--uc-sidebar-width) !important;
	max-width: var(--uc-sidebar-width) !important;
   z-index:1;
}
```
