### ISSUE TITLE
Linux应该下载哪个压缩包？

### ISSUE THREAD

**Issue by qiao-huan** [christorange/VerticalFox#52]

**Comment by qiao-huan** [comment]
试了一下，用mac的就行

**Comment by HugoPhi** [comment]
windows 也可以，只是要在里面加上：
#TabsToolbar .titlebar-button {
    display: none !important;
}
以隐藏右上角的按钮。
而且我的Ubuntu22.04上的firefox使用了Mac的压缩包，可能和其他配置冲突导致搜索栏只有一半。用windows就好了。建议都试一下。

**Comment by HugoPhi** [comment]
windows 也可以，只是要在里面加上：
```css
#TabsToolbar .titlebar-button {
display: none !important;
}
```
以隐藏右上角的按钮。
而且我的Ubuntu22.04上的firefox使用了Mac的压缩包，可能和其他配置冲突导致搜索栏只有一半。用windows就好了。建议都试一下。
