### ISSUE TITLE
Optional pinned tabs wrap broken since Sideberry v5

### ISSUE THREAD

**Issue by dko1905** [christorange/VerticalFox#66]
They renamed `PinnedDock` to `PinnedTabsBar` which breaks the following Sideberry styles:
```css
 /* Disable these two snippets below to make pinned tabs wrap when minimised */
.PinnedDock {
	flex-wrap: nowrap !important;
}

.PinnedTab {
	overflow: hidden !important;
	min-width: var(--tabs-pinned-width) !important;
}
```

**The fix**
Rename `PinnedDock` to `PinnedTabsBar`.

Ref: [#566](https://github.com/mbnuqw/sidebery/issues/566)
